sudo: required
notifications:
  email: false
language: go
go:
  - '1.9'
  - '1.10'
  - '1.11'

services:
  - docker

before_install:
  - travis_retry docker pull yandex/clickhouse-server
  - make up_docker_server
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

install:
  - make init
  - travis_retry go get -v github.com/mattn/goveralls/...

before_script:
  - export TEST_CLICKHOUSE_DSN="http://localhost:8123/default"

script:
  - make test
  - goveralls -coverprofile=coverage.out -service=travis-ci
